# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a45f43d2aad9503ec2e1e35fd6b136ff9db3bdc5f6c135b9364480bd8b868bff82298de59e108d24496016180a298fc75f8430f875c2d759c1f1afd59fbb99e5

test:
  secret_key_base: c6d552f6bf27ee6dad29089b7dc25d0b8eac831890c0427c50d66143e5391cffdc352451d8af399d07988a77793a94d47a0237a571d2d873453a20d95f83300c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
